# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun nuxt build --preset github_pages

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./.output/public

    # Deployment job
    deploy:
        # Add a dependency to the build job
        needs: build
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source
        # Deploy to the github_pages environment
        environment:
            name: github_pages
            url: ${{ steps.deployment.outputs.page_url }}
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
